### PR TITLE
Remove react-native as dependency

### PR DESCRIPTION
**Pull request by holyxiaoxin**
I am having a naming collision between react-native packages.

Take a look at: https://github.com/gcanti/tcomb-form-native/pull/85

### CODE REVIEW

**Comment by ninamanalo19** [comment]
Thanks for the contribution. I will test it and if it's okay, I'll merge it.

**Comment by holyxiaoxin** [comment]
@ninamanalo19 I have also removed an extra declaration of containerBackgroundColor props which is breaking the package.

**Comment by holyxiaoxin** [comment]
Thanks. Let me know when this gets pushed to npm so that I can point the source back.

**Comment by ninamanalo19** [comment]
Yep. I just pushed your changes in npm awhile ago. You can already check it out.

**Comment by holyxiaoxin** [comment]
Dimensions is not available to use as such. So it should be required from react native. Take a look at the other pr. Thanks.

**Pull request merged**
