### PR TITLE
Added logic to handle onStart/onEnd props, collapsePanel

### PR DESCRIPTION
**Pull request by i8wu**
For my use case I need to do some view handling while slider is being moved for performance optimization. I can help update the README as well if you'd like.

Also added collapsePanel functionality.

### CODE REVIEW

**Comment by i8wu** [comment]
@ninamanalo19 I know you're probably busy but can you review and merge this in and update npm? They're fairly minor changes. Please let me know if there's anything I can do to help you out!

**Comment by ryancoughlin** [comment]
This would be great.

**Comment by ninamanalo19** [comment]
hello sorry for the super late reply, I am really busy these days. I will check and possibly merge tonight. Thanks @i8wu for the contribution.

**Comment by SamyPesse** [comment]
Awesome 👍 

@i8wu Can you add a method `openPanel` as well ?

I doesn't look like `containerHeight` can be used to "control" this component. 

(Basically I'm trying to open/close the panel programatically).

**Comment by i8wu** [comment]
@SamyPesse Don't really have much time to look at it, but looks like there's a function reloadHeight() that you could try calling via ref.

**Pull request merged**
